version: '3'

services:
    vending_machine-frontend:
        build: ./vending_machine
        ports:
            - 8000:8000
        env_file:
            - .env-dev
        volumes:
          - ./vending_machine:/vending_machine
