version: '3'

services:
    vending_machine-db:
        image: postgres:14-alpine
        volumes:
            - ./data/postgresql:/var/lib/postgresql/data
        restart: always
        ports:
            - '9432:5432'
        env_file:
            - .env-dev

    vending_machine-web:
        build: ./vending_machine
        command: sh /vending_machine/runserver.sh
        volumes:
            - ./vending_machine:/vending_machine
            - ./vending_machine/static/:/var/www/vending_machine/static/
            - ./vending_machine/media/:/var/www/vending_machine/media/
        depends_on:
            - vending_machine-db
        env_file:
            - .env-dev
        restart: always

    vending_machine-gateway:
        container_name: vending_machine-gateway
        image: nginx:alpine
        ports:
            - '8989:80'
        volumes:
            - ./nginx-dev/:/etc/nginx/conf.d
            - ./vending_machine:/vending_machine
            - ./vending_machine/static/:/var/www/vending_machine/static/
            - ./vending_machine/media/:/var/www/vending_machine/media/
            - ./certs/:/certs
        depends_on:
            - vending_machine-web
        restart: always
